import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class CareerReportPdfGenerator {
  static const _mint = PdfColor.fromInt(0xFFB8E6D5);
  static const _black = PdfColors.black;
  static const _white = PdfColors.white;
  static const _yellow = PdfColor.fromInt(0xFFFFF9C4);
  static const _green = PdfColor.fromInt(0xFF10B981);
  static const _red = PdfColor.fromInt(0xFFF43F5E);
  static const _blue = PdfColor.fromInt(0xFF3B82F6);
  static const _purple = PdfColor.fromInt(0xFFA855F7);
  static const _lightGrey = PdfColor.fromInt(0xFFF3F4F6);

  /// [data] is the `json['data']` from GET /api/career-report/summary
  static Future<Uint8List> generate(Map<String, dynamic> data) async {
    final pdf = pw.Document();

    final student = _asMap(data['student']);
    final career = _asMap(data['careerReadiness']);
    final resume = _asMap(data['resume']);
    final learning = _asMap(data['learning']);
    final projects = _asMap(data['githubProjects']);
    final interviews = _asMap(data['mockInterview']);
    final skills = _asList(data['skills']);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(student, career),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildCareerReadiness(career),
          pw.SizedBox(height: 16),
          _buildResumeAnalysis(resume),
          pw.SizedBox(height: 16),
          _buildLearningProgress(learning),
          pw.SizedBox(height: 16),
          _buildProjects(projects),
          pw.SizedBox(height: 16),
          _buildMockInterviews(interviews),
          pw.SizedBox(height: 16),
          _buildSkills(skills),
          if ((career['aiRecommendations'] as List? ?? []).isNotEmpty) ...[
            pw.SizedBox(height: 16),
            _buildRecommendations(career['aiRecommendations'] as List),
          ],
        ],
      ),
    );

    return pdf.save();
  }

  // ── Header ──────────────────────────────────────────────────────
  static pw.Widget _buildHeader(
      Map<String, dynamic> student, Map<String, dynamic> career) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 20),
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _mint,
        border: pw.Border.all(color: _black, width: 2),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('CAMPUS++ CAREER REPORT',
                  style: pw.TextStyle(
                      fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text(student['name']?.toString() ?? 'Student',
                  style: const pw.TextStyle(fontSize: 12)),
              pw.Text(
                  '${student['course'] ?? ''} | ${student['instituteName'] ?? ''}',
                  style: const pw.TextStyle(
                      fontSize: 10, color: PdfColors.grey700)),
            ],
          ),
          pw.Container(
            padding:
                const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: pw.BoxDecoration(
              color: _yellow,
              border: pw.Border.all(color: _black, width: 1.5),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Text(
              'ID: ${student['studentId'] ?? ''}',
              style:
                  pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }

  // ── Footer ──────────────────────────────────────────────────────
  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 12),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Campus++',
              style:
                  const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style:
                  const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  // ── Section builder ─────────────────────────────────────────────
  static pw.Widget _sectionTitle(String title, {PdfColor? color}) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: pw.BoxDecoration(
        color: color ?? _black,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Text(title,
          style: pw.TextStyle(
              color: _white,
              fontSize: 13,
              fontWeight: pw.FontWeight.bold)),
    );
  }

  static pw.Widget _card({required List<pw.Widget> children}) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: _white,
        border: pw.Border.all(color: _black, width: 1.5),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: children,
      ),
    );
  }

  static pw.Widget _statRow(String label, dynamic value,
      {PdfColor? valueColor}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label,
              style: const pw.TextStyle(
                  fontSize: 10, color: PdfColors.grey700)),
          pw.Text(value?.toString() ?? 'N/A',
              style: pw.TextStyle(
                  fontSize: 11,
                  fontWeight: pw.FontWeight.bold,
                  color: valueColor ?? _black)),
        ],
      ),
    );
  }

  static pw.Widget _progressBar(double fraction,
      {PdfColor color = const PdfColor.fromInt(0xFF10B981)}) {
    final clamped = fraction.clamp(0.0, 1.0);
    final percent = (clamped * 100).round();
    return pw.Container(
      height: 10,
      decoration: pw.BoxDecoration(
        color: _lightGrey,
        borderRadius: pw.BorderRadius.circular(5),
        border: pw.Border.all(color: _black, width: 1),
      ),
      child: pw.ClipRRect(
        horizontalRadius: 5,
        verticalRadius: 5,
        child: pw.Row(
          children: [
            if (percent > 0)
              pw.Expanded(
                flex: percent,
                child: pw.Container(color: color),
              ),
            if (percent < 100)
              pw.Expanded(
                flex: 100 - percent,
                child: pw.Container(),
              ),
          ],
        ),
      ),
    );
  }

  // ── 1. Career Readiness ─────────────────────────────────────────
  static pw.Widget _buildCareerReadiness(Map<String, dynamic> career) {
    final probability =
        (career['probabilityPercent'] as num?)?.toDouble() ?? 0;
    final role = career['role']?.toString() ?? 'Software Engineer';
    final perfScore = career['performanceScore'];
    final riskLevel = career['riskLevel']?.toString();
    final trend = career['trend']?.toString();
    final strengths = _asList(career['aiStrengths']);
    final concerns = _asList(career['aiConcerns']);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('CAREER READINESS', color: _green),
        pw.SizedBox(height: 8),
        _card(children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('$role Probability',
                      style: const pw.TextStyle(
                          fontSize: 10, color: PdfColors.grey700)),
                  pw.Text(
                      probability > 0
                          ? '${probability.toStringAsFixed(1)}%'
                          : 'N/A',
                      style: pw.TextStyle(
                          fontSize: 28, fontWeight: pw.FontWeight.bold)),
                ],
              ),
              if (riskLevel != null)
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 10, vertical: 5),
                  decoration: pw.BoxDecoration(
                    color: riskLevel == 'low'
                        ? _green
                        : riskLevel == 'medium'
                            ? _yellow
                            : _red,
                    borderRadius: pw.BorderRadius.circular(6),
                    border: pw.Border.all(color: _black, width: 1),
                  ),
                  child: pw.Text('Risk: ${riskLevel.toUpperCase()}',
                      style: pw.TextStyle(
                          fontSize: 10, fontWeight: pw.FontWeight.bold)),
                ),
            ],
          ),
          pw.SizedBox(height: 8),
          _progressBar(probability / 100),
          pw.SizedBox(height: 8),
          if (perfScore != null)
            _statRow('Performance Score', perfScore),
          if (trend != null) _statRow('Trend', trend),
          if (strengths.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            pw.Text('Strengths',
                style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: _green)),
            ...strengths.map((s) => pw.Padding(
                  padding: const pw.EdgeInsets.only(top: 2),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('+ ',
                          style: pw.TextStyle(fontSize: 9, color: _green)),
                      pw.Expanded(
                          child: pw.Text(s.toString(),
                              style: const pw.TextStyle(fontSize: 9))),
                    ],
                  ),
                )),
          ],
          if (concerns.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            pw.Text('Concerns',
                style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: _red)),
            ...concerns.map((s) => pw.Padding(
                  padding: const pw.EdgeInsets.only(top: 2),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('- ',
                          style: pw.TextStyle(fontSize: 9, color: _red)),
                      pw.Expanded(
                          child: pw.Text(s.toString(),
                              style: const pw.TextStyle(fontSize: 9))),
                    ],
                  ),
                )),
          ],
        ]),
      ],
    );
  }

  // ── 2. Resume Analysis ──────────────────────────────────────────
  static pw.Widget _buildResumeAnalysis(Map<String, dynamic> resume) {
    final score = resume['score'];
    if (score == null) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('RESUME ANALYSIS', color: _blue),
          pw.SizedBox(height: 8),
          _card(children: [
            pw.Text('No resume analyzed yet.',
                style: const pw.TextStyle(
                    fontSize: 10, color: PdfColors.grey600)),
          ]),
        ],
      );
    }

    final scoreVal = (score as num).toDouble();
    final rating = resume['rating']?.toString();
    final strengths = _asList(resume['strengths']);
    final improvements = _asList(resume['criticalImprovements']);
    final missingSkills = _asList(resume['missingOrSuggestedSkills']);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('RESUME ANALYSIS', color: _blue),
        pw.SizedBox(height: 8),
        _card(children: [
          _statRow('ATS Score', '${scoreVal.toStringAsFixed(0)} / 100'),
          if (rating != null) _statRow('Rating', rating),
          pw.SizedBox(height: 6),
          _progressBar(scoreVal / 100, color: _blue),
          if (strengths.isNotEmpty) ...[
            pw.SizedBox(height: 10),
            pw.Text('Strengths',
                style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: _green)),
            ...strengths.map((s) => pw.Padding(
                  padding: const pw.EdgeInsets.only(top: 2),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('+ ',
                          style: pw.TextStyle(fontSize: 9, color: _green)),
                      pw.Expanded(
                          child: pw.Text(s.toString(),
                              style: const pw.TextStyle(fontSize: 9))),
                    ],
                  ),
                )),
          ],
          if (improvements.isNotEmpty) ...[
            pw.SizedBox(height: 10),
            pw.Text('Critical Improvements',
                style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: _red)),
            ...improvements.map((s) => pw.Padding(
                  padding: const pw.EdgeInsets.only(top: 2),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('- ',
                          style: pw.TextStyle(fontSize: 9, color: _red)),
                      pw.Expanded(
                          child: pw.Text(s.toString(),
                              style: const pw.TextStyle(fontSize: 9))),
                    ],
                  ),
                )),
          ],
          if (missingSkills.isNotEmpty) ...[
            pw.SizedBox(height: 10),
            pw.Text('Suggested Skills',
                style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: _purple)),
            pw.SizedBox(height: 4),
            pw.Wrap(
              spacing: 6,
              runSpacing: 4,
              children: missingSkills
                  .map((s) => pw.Container(
                        padding: const pw.EdgeInsets.symmetric(
                            horizontal: 8, vertical: 3),
                        decoration: pw.BoxDecoration(
                          color: _lightGrey,
                          borderRadius: pw.BorderRadius.circular(6),
                          border: pw.Border.all(color: _black, width: 1),
                        ),
                        child: pw.Text(s.toString(),
                            style: const pw.TextStyle(fontSize: 8)),
                      ))
                  .toList(),
            ),
          ],
        ]),
      ],
    );
  }

  // ── 3. Learning Progress ────────────────────────────────────────
  static pw.Widget _buildLearningProgress(Map<String, dynamic> learning) {
    final totalPaths = learning['totalPaths'] as num? ?? 0;
    final completedPaths = learning['completedPaths'] as num? ?? 0;
    final avgProgress =
        (learning['averageProgressPercent'] as num?)?.toDouble() ?? 0;
    final completedSteps = learning['completedSteps'] as num? ?? 0;
    final totalSteps = learning['totalSteps'] as num? ?? 0;
    final topics = _asList(learning['topics']);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('LEARNING PROGRESS', color: _purple),
        pw.SizedBox(height: 8),
        _card(children: [
          _statRow(
              'Learning Paths', '$completedPaths / $totalPaths completed'),
          pw.SizedBox(height: 4),
          _progressBar(
              totalPaths > 0 ? completedPaths / totalPaths : 0,
              color: _purple),
          pw.SizedBox(height: 8),
          _statRow(
              'Average Progress', '${avgProgress.toStringAsFixed(1)}%'),
          _statRow('Steps Completed', '$completedSteps / $totalSteps'),
          if (topics.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            pw.Text('Topics',
                style: pw.TextStyle(
                    fontSize: 10, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 4),
            ...topics.take(8).map((t) {
              final topic = t is Map ? t : {};
              final name = topic['topic']?.toString() ?? '';
              final status = topic['status']?.toString() ?? '';
              final progress = (topic['progress'] as num?)?.toDouble() ?? 0;
              return pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 2),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Expanded(
                            child: pw.Text(name,
                                style: const pw.TextStyle(fontSize: 9))),
                        pw.Text(
                            '${progress.toStringAsFixed(0)}% ($status)',
                            style: pw.TextStyle(
                                fontSize: 9,
                                fontWeight: pw.FontWeight.bold)),
                      ],
                    ),
                    pw.SizedBox(height: 2),
                    _progressBar(progress / 100, color: _purple),
                  ],
                ),
              );
            }),
          ],
        ]),
      ],
    );
  }

  // ── 4. Projects ─────────────────────────────────────────────────
  static pw.Widget _buildProjects(Map<String, dynamic> projects) {
    final total = projects['projectCount'] as num? ?? 0;
    final evaluated = projects['evaluatedProjectCount'] as num? ?? 0;
    final repos = projects['linkedRepositories'] as num? ?? 0;
    final projectList = _asList(projects['projects']);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('PROJECTS',
            color: const PdfColor.fromInt(0xFFF59E0B)),
        pw.SizedBox(height: 8),
        _card(children: [
          _statRow('Total Projects', '$total'),
          _statRow('Evaluated', '$evaluated'),
          _statRow('Linked Repositories', '$repos'),
          if (total > 0)
            _progressBar(evaluated / total,
                color: const PdfColor.fromInt(0xFFF59E0B)),
          if (projectList.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            ...projectList.take(6).map((p) {
              final proj = p is Map ? p : {};
              final name = proj['name']?.toString() ?? 'Unnamed';
              final grade = proj['grade']?.toString();
              final score = proj['score'];
              final status = proj['status']?.toString() ?? '';
              return pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 2),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Expanded(
                        child: pw.Text(name,
                            style: const pw.TextStyle(fontSize: 9))),
                    pw.Text(
                        grade != null
                            ? 'Grade $grade ($score/100)'
                            : status,
                        style: pw.TextStyle(
                            fontSize: 9,
                            fontWeight: pw.FontWeight.bold)),
                  ],
                ),
              );
            }),
          ],
        ]),
      ],
    );
  }

  // ── 5. Mock Interviews ──────────────────────────────────────────
  static pw.Widget _buildMockInterviews(Map<String, dynamic> interviews) {
    final total = interviews['sessionsCompleted'] as num? ?? 0;
    final avgScore =
        (interviews['averageScore'] as num?)?.toDouble();
    final sessions = _asList(interviews['latestSessions']);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('MOCK INTERVIEWS',
            color: const PdfColor.fromInt(0xFF6366F1)),
        pw.SizedBox(height: 8),
        _card(children: [
          _statRow('Sessions Completed', '$total'),
          _statRow('Average Score',
              avgScore != null ? '${avgScore.toStringAsFixed(1)} / 100' : 'N/A'),
          if (sessions.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            pw.Text('Recent Sessions',
                style: pw.TextStyle(
                    fontSize: 10, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 4),
            ...sessions.take(5).map((s) {
              final session = s is Map ? s : {};
              final score = session['score'];
              final qCount = session['questionCount'] ?? '';
              return pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 2),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('$qCount questions',
                        style: const pw.TextStyle(fontSize: 9)),
                    pw.Text('Score: $score/100',
                        style: pw.TextStyle(
                            fontSize: 9,
                            fontWeight: pw.FontWeight.bold)),
                  ],
                ),
              );
            }),
          ],
        ]),
      ],
    );
  }

  // ── 6. Skills ───────────────────────────────────────────────────
  static pw.Widget _buildSkills(List<dynamic> skills) {
    if (skills.isEmpty) return pw.SizedBox();

    final strong = skills.where((s) => s is Map && s['status'] == 'strong').toList();
    final improve = skills.where((s) => s is Map && s['status'] == 'improve').toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('SKILLS',
            color: const PdfColor.fromInt(0xFF0EA5E9)),
        pw.SizedBox(height: 8),
        _card(children: [
          if (strong.isNotEmpty) ...[
            pw.Text('Strong Skills',
                style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: _green)),
            pw.SizedBox(height: 4),
            pw.Wrap(
              spacing: 6,
              runSpacing: 4,
              children: strong.map((s) {
                final name =
                    s is Map ? s['name']?.toString() ?? '' : s.toString();
                return pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 8, vertical: 3),
                  decoration: pw.BoxDecoration(
                    color: _mint,
                    borderRadius: pw.BorderRadius.circular(6),
                    border: pw.Border.all(color: _black, width: 1),
                  ),
                  child: pw.Text(name,
                      style: const pw.TextStyle(fontSize: 8)),
                );
              }).toList(),
            ),
          ],
          if (improve.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            pw.Text('Needs Improvement',
                style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: _red)),
            pw.SizedBox(height: 4),
            pw.Wrap(
              spacing: 6,
              runSpacing: 4,
              children: improve.map((s) {
                final name =
                    s is Map ? s['name']?.toString() ?? '' : s.toString();
                return pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 8, vertical: 3),
                  decoration: pw.BoxDecoration(
                    color: _yellow,
                    borderRadius: pw.BorderRadius.circular(6),
                    border: pw.Border.all(color: _black, width: 1),
                  ),
                  child: pw.Text(name,
                      style: const pw.TextStyle(fontSize: 8)),
                );
              }).toList(),
            ),
          ],
        ]),
      ],
    );
  }

  // ── 7. Recommendations ──────────────────────────────────────────
  static pw.Widget _buildRecommendations(List<dynamic> recs) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('AI RECOMMENDATIONS', color: _red),
        pw.SizedBox(height: 8),
        _card(children: [
          ...recs.asMap().entries.map((e) {
            return pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 3),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Container(
                    width: 18,
                    height: 18,
                    decoration: pw.BoxDecoration(
                      color: _mint,
                      borderRadius: pw.BorderRadius.circular(4),
                      border: pw.Border.all(color: _black, width: 1),
                    ),
                    child: pw.Center(
                      child: pw.Text('${e.key + 1}',
                          style: pw.TextStyle(
                              fontSize: 8,
                              fontWeight: pw.FontWeight.bold)),
                    ),
                  ),
                  pw.SizedBox(width: 8),
                  pw.Expanded(
                    child: pw.Text(e.value.toString(),
                        style: const pw.TextStyle(fontSize: 9)),
                  ),
                ],
              ),
            );
          }),
        ]),
      ],
    );
  }

  // ── Helpers ─────────────────────────────────────────────────────
  static Map<String, dynamic> _asMap(dynamic value) {
    if (value is Map<String, dynamic>) return value;
    if (value is Map) return Map<String, dynamic>.from(value);
    return {};
  }

  static List<dynamic> _asList(dynamic value) {
    if (value is List) return value;
    return [];
  }
}
